export const arquivoData = [
  {
    ID: 0,
    DS_ARQUIVO: "Maquilhagem completa",
    DS_RESUMO: "Maquilhagem completa",
    DS_DESCRICAO: "Maquilhagem completa",
    CD_TIPO: 1,
    DS_LINK_THUMBNAIL: "link Thumb",
    DS_TEXTO_THUMBNAIL: "Texto Yhumb",
    DS_LINK_ARQUIVO: "https://www.adobe.com/br",
    DS_TEXTO_LINK: "Vídeo de maquilhagem",
    createdAt: "25/05/2022",
  },
  {
    ID: 1,
    DS_ARQUIVO: "Maquilhagem completa",
    DS_RESUMO: "Maquilhagem completa",
    DS_DESCRICAO: "Maquilhagem completa",
    CD_TIPO: 1,
    DS_LINK_THUMBNAIL: "link Thumb",
    DS_TEXTO_THUMBNAIL: "Texto Yhumb",
    DS_LINK_ARQUIVO: "https://www.adobe.com/br",
    DS_TEXTO_LINK: "Vídeo de maquilhagem",
    createdAt: "25/05/2022",
  },
  {
    ID: 2,
    DS_ARQUIVO: "Maquilhagem completa",
    DS_RESUMO: "Maquilhagem completa",
    DS_DESCRICAO: "Maquilhagem completa",
    CD_TIPO: 1,
    DS_LINK_THUMBNAIL: "link Thumb",
    DS_TEXTO_THUMBNAIL: "Texto Yhumb",
    DS_LINK_ARQUIVO: "https://www.adobe.com/br",
    DS_TEXTO_LINK: "Vídeo de maquilhagem",
    createdAt: "25/05/2022",
  },
  {
    ID: 3,
    DS_ARQUIVO: "Maquilhagem completa",
    DS_RESUMO: "Maquilhagem completa",
    DS_DESCRICAO: "Maquilhagem completa",
    CD_TIPO: 1,
    DS_LINK_THUMBNAIL: "link Thumb",
    DS_TEXTO_THUMBNAIL: "Texto Yhumb",
    DS_LINK_ARQUIVO: "https://www.adobe.com/br",
    DS_TEXTO_LINK: "Vídeo de maquilhagem",
    createdAt: "25/05/2022",
  },
  {
    ID: 4,
    DS_ARQUIVO: "Maquilhagem completa",
    DS_RESUMO: "Maquilhagem completa",
    DS_DESCRICAO: "Maquilhagem completa",
    CD_TIPO: 1,
    DS_LINK_THUMBNAIL: "link Thumb",
    DS_TEXTO_THUMBNAIL: "Texto Yhumb",
    DS_LINK_ARQUIVO: "https://www.adobe.com/br",
    DS_TEXTO_LINK: "Vídeo de maquilhagem",
    createdAt: "25/05/2022",
  },

  {
    ID: 5,
    DS_ARQUIVO: "Maquilhagem completa",
    DS_RESUMO: "Maquilhagem completa",
    DS_DESCRICAO: "Maquilhagem completa",
    CD_TIPO: 1,
    DS_LINK_THUMBNAIL: "link Thumb",
    DS_TEXTO_THUMBNAIL: "Texto Yhumb",
    DS_LINK_ARQUIVO: "https://www.adobe.com/br",
    DS_TEXTO_LINK: "Vídeo de maquilhagem",
    createdAt: "25/05/2022",
  },
];
