export const modulosData = [
  {
    ID: 0,
    DS_MODULO: "Maquilhagem",
    DS_RESUMO: "Maquilhagem completa para criar seu próprio negócio",
    DS_DESCRICAO_DETALHADA: "Maquilhagem Completa",
    CD_ORDENACAO: 1,
    CD_REQUER_CONCLUSAO_ANTERIOR: 2,
    CD_PROVA_AO_FINAL: 1,
    VL_LIBERAR_PROVA_PORCENTAGEM_CONCLUSAO: 80,
    VL_NOTA_MINIMA_CONCLUIR: 70,
    DS_LINK_IMAGEM:
      "https://ncultura.pt/wp-content/uploads/2021/06/9-erros-de-maquilhagem-mais-comuns-00.jpg",
    DS_TEXTO_IMAGEM: "Maquilhagem",
    NR_DIAS_PARA_CONCLUIR: 90,
    NR_TENTATIVAS_MAX_PROVA: 10,
    VL_CARGA_HORARIA: "10",
    ID_CERTIFICADO: 0,
    ID_CURSO: 2,
    createdAt: "25/05/2022",
  },
  {
    ID: 1,
    DS_MODULO: "Maquilhagem",
    DS_RESUMO: "Maquilhagem completa para criar seu próprio negócio",
    DS_DESCRICAO_DETALHADA: "Maquilhagem Completa",
    CD_ORDENACAO: 1,
    CD_REQUER_CONCLUSAO_ANTERIOR: 2,
    CD_PROVA_AO_FINAL: 1,
    VL_LIBERAR_PROVA_PORCENTAGEM_CONCLUSAO: 80,
    VL_NOTA_MINIMA_CONCLUIR: 70,
    DS_LINK_IMAGEM:
      "https://ncultura.pt/wp-content/uploads/2021/06/9-erros-de-maquilhagem-mais-comuns-00.jpg",
    DS_TEXTO_IMAGEM: "Maquilhagem",
    NR_DIAS_PARA_CONCLUIR: 90,
    NR_TENTATIVAS_MAX_PROVA: 10,
    VL_CARGA_HORARIA: "10",
    ID_CERTIFICADO: 0,
    ID_CURSO: 2,
    createdAt: "25/05/2022",
  },
  {
    ID: 2,
    DS_MODULO: "Maquilhagem",
    DS_RESUMO: "Maquilhagem completa para criar seu próprio negócio",
    DS_DESCRICAO_DETALHADA: "Maquilhagem Completa",
    CD_ORDENACAO: 1,
    CD_REQUER_CONCLUSAO_ANTERIOR: 2,
    CD_PROVA_AO_FINAL: 1,
    VL_LIBERAR_PROVA_PORCENTAGEM_CONCLUSAO: 80,
    VL_NOTA_MINIMA_CONCLUIR: 70,
    DS_LINK_IMAGEM:
      "https://ncultura.pt/wp-content/uploads/2021/06/9-erros-de-maquilhagem-mais-comuns-00.jpg",
    DS_TEXTO_IMAGEM: "Maquilhagem",
    NR_DIAS_PARA_CONCLUIR: 90,
    NR_TENTATIVAS_MAX_PROVA: 10,
    VL_CARGA_HORARIA: "10",
    ID_CERTIFICADO: 0,
    ID_CURSO: 2,
    createdAt: "25/05/2022",
  },
  {
    ID: 3,
    DS_MODULO: "Maquilhagem",
    DS_RESUMO: "Maquilhagem completa para criar seu próprio negócio",
    DS_DESCRICAO_DETALHADA: "Maquilhagem Completa",
    CD_ORDENACAO: 1,
    CD_REQUER_CONCLUSAO_ANTERIOR: 2,
    CD_PROVA_AO_FINAL: 1,
    VL_LIBERAR_PROVA_PORCENTAGEM_CONCLUSAO: 80,
    VL_NOTA_MINIMA_CONCLUIR: 70,
    DS_LINK_IMAGEM:
      "https://ncultura.pt/wp-content/uploads/2021/06/9-erros-de-maquilhagem-mais-comuns-00.jpg",
    DS_TEXTO_IMAGEM: "Maquilhagem",
    NR_DIAS_PARA_CONCLUIR: 90,
    NR_TENTATIVAS_MAX_PROVA: 10,
    VL_CARGA_HORARIA: "10",
    ID_CERTIFICADO: 0,
    ID_CURSO: 2,
    createdAt: "25/05/2022",
  },
  {
    ID: 4,
    DS_MODULO: "Maquilhagem",
    DS_RESUMO: "Maquilhagem completa para criar seu próprio negócio",
    DS_DESCRICAO_DETALHADA: "Maquilhagem Completa",
    CD_ORDENACAO: 1,
    CD_REQUER_CONCLUSAO_ANTERIOR: 2,
    CD_PROVA_AO_FINAL: 1,
    VL_LIBERAR_PROVA_PORCENTAGEM_CONCLUSAO: 80,
    VL_NOTA_MINIMA_CONCLUIR: 70,
    DS_LINK_IMAGEM:
      "https://ncultura.pt/wp-content/uploads/2021/06/9-erros-de-maquilhagem-mais-comuns-00.jpg",
    DS_TEXTO_IMAGEM: "Maquilhagem",
    NR_DIAS_PARA_CONCLUIR: 90,
    NR_TENTATIVAS_MAX_PROVA: 10,
    VL_CARGA_HORARIA: "10",
    ID_CERTIFICADO: 0,
    ID_CURSO: 2,
    createdAt: "25/05/2022",
  },
];
