export const aulasData = [
  {
    ID: 0,
    ID_MODULO: 2,
    VL_CONSIDERAR_COMPLETA: 1,
    CD_ORDENACAO: 0,
    DS_DESCRICAO: "Automaquilhagem",
    DS_RESUMO: "Aula para aperfeiçoar sobre automaquilhagem",
    CD_STATUS: 1,
    VL_ATUAL: 0,
    createdAt: "25/05/2022",
  },
  {
    ID: 1,
    ID_MODULO: 2,
    VL_CONSIDERAR_COMPLETA: 1,
    CD_ORDENACAO: 0,
    DS_DESCRICAO: "Automaquilhagem",
    DS_RESUMO: "Aula para aperfeiçoar sobre automaquilhagem",
    CD_STATUS: 1,
    VL_ATUAL: 0,
    createdAt: "25/05/2022",
  },
  {
    ID: 2,
    ID_MODULO: 2,
    VL_CONSIDERAR_COMPLETA: 1,
    CD_ORDENACAO: 0,
    DS_DESCRICAO: "Automaquilhagem",
    DS_RESUMO: "Aula para aperfeiçoar sobre automaquilhagem",
    CD_STATUS: 1,
    VL_ATUAL: 0,
    createdAt: "25/05/2022",
  },
  {
    ID: 3,
    ID_MODULO: 2,
    VL_CONSIDERAR_COMPLETA: 1,
    CD_ORDENACAO: 0,
    DS_DESCRICAO: "Automaquilhagem",
    DS_RESUMO: "Aula para aperfeiçoar sobre automaquilhagem",
    CD_STATUS: 1,
    VL_ATUAL: 0,
    createdAt: "25/05/2022",
  },
  {
    ID: 4,
    ID_MODULO: 2,
    VL_CONSIDERAR_COMPLETA: 1,
    CD_ORDENACAO: 0,
    DS_DESCRICAO: "Automaquilhagem",
    DS_RESUMO: "Aula para aperfeiçoar sobre automaquilhagem",
    CD_STATUS: 1,
    VL_ATUAL: 0,
    createdAt: "25/05/2022",
  },
];
